config/routes.rb
Rails.application.routes.draw do
    mount Resque::Server, at: '/jobs'

    get '/task/:uuid/accept', to: 'tasks#accept', as: 'accept_task'
    get '/task/:uuid/cancel', to: 'tasks#cancel', as: 'cancel_task'
    get '/tasks/multiple', to: 'tasks#multiple'
    post '/callback', to: 'workflow#callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    def self.from_json(json_str)
        Rails.logger.info "Received task:"
        Rails.logger.info json_str

        task_hash = JSON.parse(json_str)

        tasks = []
    
        if task_hash.key? 'collection' # Multiple tasks
            task_hash['collection'].each do |task|
                tasks << task_from_hash(task)
            end
        else
            tasks << task_from_hash(task_hash)
        end
        tasks
    end

    private

    def self.task_from_hash(h)
        Task.create(
            user_url: h['links'].select {|l| l['rel'] == 'user' }.first.to_json,
            task_type: h['type'],
            owner_url: h['links'].select {|l| l['rel'] == 'user' }.first.to_json,
            task_state: h['state'],
            target_url: h['links'].select {|l| l['rel'] == 'target' }.first.to_json,
            continue_url: h['links'].select {|l| l['rel'] == 'continue' }.first.to_json,
            cancel_url: h['links'].select {|l| l['rel'] == 'cancel' }.first.to_json,
            active: true,
            uuid: SecureRandom.uuid
        )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    protect_from_forgery with: :null_session

    def accept
        task = Task.find_by_uuid(params[:uuid])
        unless validate_task(task)
            @message = "Requested task ID is not valid!"
        else
            @message = "Your task is being processed. You will see progress in the Abiquo UI."
            AcceptTaskJob.perform_later([task])
        end
    end

    def cancel
        task = Task.find_by_uuid(params[:uuid])
        unless validate_task(task)
            @message = "Requested task ID is not valid!"
        else
            @message = "Your task is being processed. You will see progress in the Abiquo UI."
            CancelTaskJob.perform_later([task])
        end
    end

    def multiple
        task_uuids = params[:tasks].split(',')
        tasks = Task.find_by_uuid(task_uuids)
        case params[:task_action]
        when 'accept'
            AcceptTaskJob.perform_later(tasks)
        when 'cancel'
            CancelTaskJob.perform_later(tasks)
        end
        @message = "Your tasks are being processed. You will see progress in the Abiquo UI."
    end

    private 

    def validate_task(task)
        task && task.active?
    end
end

app/controllers/workflow_controller.rb
class WorkflowController < ApplicationController
    protect_from_forgery with: :null_session

    def callback
        tasks = Task.from_json(request.body.read)
        ProcessTasksJob.perform_later(tasks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/workflow_helper.rb
module WorkflowHelper
end

app/views/default/send_approval_email.html.erb
<html>
  <head>
    <title>Abiquo workflow acceptance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- Bootstrap -->
  </head>
  <body bgcolor="#E6E6FA" style="margin: 0;font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;font-size: 14px;line-height: 20px;color: #333;background-color: #fff">
    <p style="margin: 0 0 10px"/>
      <div class="container well well-large" style="padding: 19px 19px;width: 940px;margin-right: auto;margin-left: auto;min-height: 20px;margin-bottom: 20px;background-color: #f5f5f5;border: 1px solid #e3e3e3;-webkit-border-radius: 6px;-moz-border-radius: 6px;border-radius: 6px;-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);-moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05)">
        <p class="text-center" style="margin: 0 0 10px;text-align: center"/>
          <h1 style="margin: 10px 0;font-family: inherit;font-weight: bold;line-height: 20px;color: inherit;text-rendering: optimizelegibility;font-size: 38.5px">Abiquo Task</h1>
          <p style="margin: 0 0 10px">
            <span>A new task has been submitted by user
              <span class="label label-info" style="display: inline-block;padding: 2px 4px;font-size: 11.844px;font-weight: bold;line-height: 14px;color: #fff;text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);white-space: nowrap;vertical-align: baseline;background-color: #3a87ad;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px"><%= @tasks[:username] %>
              </span> requesting to
              <span class="label label-warning" style="display: inline-block;padding: 2px 4px;font-size: 11.844px;font-weight: bold;line-height: 14px;color: #fff;text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);white-space: nowrap;vertical-align: baseline;background-color: #f89406;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px"><%= @tasks[:task_type] %></span> on<br/>
              <span class="label label-warning" style="display: inline-block;padding: 2px 4px;font-size: 11.844px;font-weight: bold;line-height: 14px;color: #fff;text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);white-space: nowrap;vertical-align: baseline;background-color: #00CC00;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px">Enterprise <%= @tasks['enterprise'] %> &gt; VDC <%= @tasks[:vdc_name] %> (in datacenter <%= @tasks[:dc_name] %>) &gt; vApp <%= @tasks[:vapp_name] %></span>
              <br/><br/>
              The request consists on:
            </span>
          </p>
          <p style="margin: 0 0 10px"></p>
          <div class="bs-docs-example">
            <table class="table table-condensed" style="max-width: 100%;background-color: transparent;border-collapse: collapse;border-spacing: 0;width: 100%;margin-bottom: 20px">
              <thead>
                <tr>
                  <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">VM Name</th>
                  <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">CPU</th>
                  <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">RAM</th>
                  <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">HD</th>
                  <% if @render_links %>
                  <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">Action</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <!-- FOR EACH VM -->
                <% @tasks[:vm_details].each do |vm| %>
                <tr>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><strong style="font-weight: bold"><%= vm[:name] %></strong> <%= '(Persistent VM)' if vm[:persistent] %></td>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><%= vm[:cpu] %></td>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><%= vm[:ram] %></td>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"></td>
                  <% if @render_links %>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: center;vertical-align: center;border-top: 1px solid #ddd" rowspan="<%= vm[:disks].count + 1 %>"><div>
                    <%= link_to 'Accept', accept_task_url(vm[:task]), style: 'background-color:#0dbf22;border-radius:12px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:30px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;', only_path: true %>
                  </td>
                  <td style="padding: 4px 5px;line-height: 20px;text-align: center;vertical-align: center;border-top: 1px solid #ddd" rowspan="<%= vm[:disks].count + 1 %>">
                    <%= link_to 'Cancel', cancel_task_url(vm[:task]), style: 'background-color:#bf0f32;border-radius:12px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:30px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;', only_path: true %>
                  </td>
                  <% end %>
                </tr>
                <!-- FOR EACH DISK -->
                <% vm[:disks].each do |disk| %>
                <tr>
                  <td style="padding: 1px 40px;line-height: 20px;text-align: left;vertical-align: top;font-size:90%"><%= disk[:type] %> <%= disk[:sequence] %> <%= disk[:name].nil? ? '(No Name)' : disk[:name] %></td>
                  <td></td>
                  <td></td>
                  <td style="padding: 1px 5px;line-height: 20px;text-align: left;vertical-align: top;font-size:90%"><%= number_to_human_size(disk[:size] * 1024 * 1024 ) %></td>
                </tr>
                <% end %>
                <!-- END FOR EACH DISK -->
                <% end %>
                <!-- END FOR EACH VM -->
              </tbody>
            </table>
          </div>
          <% if @render_links %>
          <p style="margin: 0 0 10px">
            <span>Alternatively, you can bulk accept or deny all requests listed above using the buttons below.</span>
          </p>
          <%= link_to 'Accept all', tasks_multiple_url(task_action: 'accept', tasks: @tasks[:vm_details].map {|t| t[:task]}.join(',')), style: 'background-color:#0dbf22;border-radius:12px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:30px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;', only_path: true %>
          <%= link_to 'Cancel all', tasks_multiple_url(task_action: 'cancel', tasks: @tasks[:vm_details].map {|t| t[:task]}.join(',')), style: 'background-color:#bf0f32;border-radius:12px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:30px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;', only_path: true %>
          <% end %>
          <script src="http://code.jquery.com/jquery.js"/><script src="http://twitter.github.io/bootstrap/assets/js/bootstrap.min.js"/>
        </p>
      </div>
    </p>
  </body>
</html>

app/views/default/send_requester_email.html.erb
<html>
  <head>
    <title>Abiquo workflow acceptance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- Bootstrap -->
  </head>
  <body bgcolor="#E6E6FA" style="margin: 0;font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;font-size: 14px;line-height: 20px;color: #333;background-color: #fff">
    <p style="margin: 0 0 10px"/><div class="container well well-large" style="padding: 19px 19px;width: 940px;margin-right: auto;margin-left: auto;min-height: 20px;margin-bottom: 20px;background-color: #f5f5f5;border: 1px solid #e3e3e3;-webkit-border-radius: 6px;-moz-border-radius: 6px;border-radius: 6px;-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);-moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05)">
      <p class="text-center" style="margin: 0 0 10px;text-align: center"/><h1 style="margin: 10px 0;font-family: inherit;font-weight: bold;line-height: 20px;color: inherit;text-rendering: optimizelegibility;font-size: 38.5px">Abiquo Task</h1>
        <p style="margin: 0 0 10px"><span>Your tasks with action <%= @tasks[:task_type] %> have been attended by the designated roles. The result of the transaction is: </span></p>
        <p style="margin: 0 0 10px"></p>
        <div class="bs-docs-example">
          <table class="table table-condensed" style="max-width: 100%;background-color: transparent;border-collapse: collapse;border-spacing: 0;width: 100%;margin-bottom: 20px">
            <thead>
              <tr>
                <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">VM Name</th>
                <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">CPU</th>
                <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">RAM</th>
                <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">HD</th>
                <th style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: bottom;border-top: 0;font-weight: bold">Action</th>
              </tr>
            </thead>
            <tbody>
              <!-- FOR EACH VM -->
              <% @tasks[:vm_details].each do |vm| %>
              <tr>
                <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><strong style="font-weight: bold"><%= vm[:name] %></strong></td>
                <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><%= vm[:cpu] %></td>
                <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><%= vm[:ram] %></td>
                <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"></td>
                <td style="padding: 4px 5px;line-height: 20px;text-align: left;vertical-align: top;border-top: 1px solid #ddd"><%= vm[:task_action] %></td>
              </tr>
              <% end %>
              <!-- END FOR EACH VM -->
            </tbody>
          </table>
        </div>
        <p style="margin: 0 0 10px">
          <span>Go to the Abiquo UI and select the Events tab for more information.</span>
        </p>
        <script src="http://code.jquery.com/jquery.js"/><script src="http://twitter.github.io/bootstrap/assets/js/bootstrap.min.js"/>
      </div>
    </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Workflow Request</title>
        <style type="text/css">
        body
        {
        background:#ffffff url('<%= image_url "monster.jpg" %>') no-repeat left top;
        margin-left: 0%;
        margin-right: 0%;
        font-family: sans-serif;
        }
        .downFrame
        {
        background:#FFD249;
        width: 100%;
        position: absolute;
        bottom: 0px;
        top: 60%;
        margin-left: 0px;
        margin-right: 0px;
        }
        .WFRequest
        {
        text-align:left;
        width: 50%;
        height: 20%;
        margin-left: 45%;
        margin-top: 13%;
        font-family:"Times New Roman", Times, serif;
        font-size: 200%;
        }
        </style>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/tasks/accept.html.erb
<div class="WFRequest">
    <p>
        <%= @message %>
    </p>
</div>
<div class="downFrame"/>

app/views/tasks/cancel.html.erb
<div class="WFRequest">
    <p>
        <%= @message %>
    </p>
</div>
<div class="downFrame"/>

app/views/tasks/multiple.html.erb
<div class="WFRequest">
    <p>
        <%= @message %>
    </p>
</div>
<div class="downFrame"/>